version: '3.9'

services:
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_prod
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - .:/website
    env_file:
      - .env_prod
    depends_on:
      - database

volumes:
  postgres_data: