version: '3.9'
services:
        db:
                image: 'postgres:14.4-bullseye'
                ports:
                        - "5432:5432"
                env_file:
                        - .env
                volumes:
                        - db-data/:/var/lib/postgresql/data
        web:
                build: .
                command: python /code/manage.py runserver 0.0.0.0:8000
                env_file:
                        - .env
                volumes:
                        - .:/code
                ports:
                        - "8000:8000"
                depends_on:
                        - db
volumes:
        db-data: