version: '3.8'

services:
        web:
                build: .
                command: python /code/manage.py runserver 0.0.0.0:8000
                env_file:
                        - .env
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                depends_on:
                        - db
        database:
                image: 'postgres:latest'
                ports:
                        - 5801:5432
                env_file:
                        - .env

                volumes:
                        - ./db-data/:/var/lib/postgresql/data/
volumes:
        postgres_data:
